// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArpGxTlHeqBHfBkRHwpptZJ6tO6qFnOxY',
    appId: '1:606194809150:android:96550380224b752f78546f',
    messagingSenderId: '606194809150',
    projectId: 'safee-meet',
    storageBucket: 'safee-meet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzR-hJTshAO7fJF4G1huZ4khqi3XmhWLI',
    appId: '1:606194809150:ios:4d7daa5973a94d0978546f',
    messagingSenderId: '606194809150',
    projectId: 'safee-meet',
    storageBucket: 'safee-meet.firebasestorage.app',
    iosBundleId: 'solutionbowl.com.safeeMeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAsV90UIGlhFRA94OZk8w_Glf5BUPI4E0',
    appId: '1:606194809150:web:cf9f995c0bcaa26378546f',
    messagingSenderId: '606194809150',
    projectId: 'safee-meet',
    authDomain: 'safee-meet.firebaseapp.com',
    storageBucket: 'safee-meet.firebasestorage.app',
    measurementId: 'G-6GGJWX63N3',
  );
}
